# Пример конфигурационного файла для ClearScan
subnets:
  - "10.0.0.0/24"
  - "192.168.1.0/24"
ports:
  - 22
  - 80
  - 443
database_path: '/opt/clearscan/clearscan.db'
telegram_bot_token: 'your_telegram_bot_token'
scan_interval: 3600
nmap_path: '/usr/bin/nmap'
http_auth_username: 'admin'
http_auth_password: 'password'
